### ISSUE TITLE
Unable to log in with an emoji in your steamname.

### ISSUE THREAD

**Issue by Sennel** [Bouncyrock/Temp-Public-TS-Issue-Tracker#1]
If you have an emoji in your steam name like "Test me 🎃" the login will fail.

**Comment by cbaggers** [comment]
What is interesting is that the failure on the backend looks more like a failed pattern match than a unicode issue. Poking around now

**Comment by cbaggers** [comment]
Ah the pattern match was a different bug. When the game signs you up it uses with your talespire alias being your current Steam profile name. It then is independent of steam's naming. But I had some code expecting the latest and old name to match.
Fixed that at least so thankyou

**Comment by cbaggers** [comment]
```
Baggers: hey man, to create this bug did you:
- start TS without a unicode name
- change your steam name to have unicode
- start TS again
[11:09 AM] Baggers: ?
[11:09 AM] Sen-Commander: Yes
[11:09 AM] Baggers: RIGHT!
[11:09 AM] Baggers: emojis are fine
[11:09 AM] Baggers: TS might not like rendering them
[11:09 AM] Baggers: but the backend is ok
```

Ok so the deal is that the above bug was the problem. Initially you logged in with one steam then and then a different one. It just happened to have an emoji in it but the backend doesnt mind. It just freaked out because of the name change

**Comment by cbaggers** [comment]
Closing for now, please reopen if this reoccurs
